package com.meilancycling.mema.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.meilancycling.mema.db.AuthorEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTHOR_ENTITY".
*/
public class AuthorEntityDao extends AbstractDao<AuthorEntity, Long> {

    public static final String TABLENAME = "AUTHOR_ENTITY";

    /**
     * Properties of entity AuthorEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, long.class, "userId", false, "USER_ID");
        public final static Property TimeOut = new Property(2, String.class, "timeOut", false, "TIME_OUT");
        public final static Property Token = new Property(3, String.class, "token", false, "TOKEN");
        public final static Property PullToken = new Property(4, String.class, "pullToken", false, "PULL_TOKEN");
        public final static Property PlatformType = new Property(5, int.class, "platformType", false, "PLATFORM_TYPE");
    }


    public AuthorEntityDao(DaoConfig config) {
        super(config);
    }
    
    public AuthorEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTHOR_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"TIME_OUT\" TEXT," + // 2: timeOut
                "\"TOKEN\" TEXT," + // 3: token
                "\"PULL_TOKEN\" TEXT," + // 4: pullToken
                "\"PLATFORM_TYPE\" INTEGER NOT NULL );"); // 5: platformType
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTHOR_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AuthorEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String timeOut = entity.getTimeOut();
        if (timeOut != null) {
            stmt.bindString(3, timeOut);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(4, token);
        }
 
        String pullToken = entity.getPullToken();
        if (pullToken != null) {
            stmt.bindString(5, pullToken);
        }
        stmt.bindLong(6, entity.getPlatformType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AuthorEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
 
        String timeOut = entity.getTimeOut();
        if (timeOut != null) {
            stmt.bindString(3, timeOut);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(4, token);
        }
 
        String pullToken = entity.getPullToken();
        if (pullToken != null) {
            stmt.bindString(5, pullToken);
        }
        stmt.bindLong(6, entity.getPlatformType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AuthorEntity readEntity(Cursor cursor, int offset) {
        AuthorEntity entity = new AuthorEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // timeOut
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // token
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // pullToken
            cursor.getInt(offset + 5) // platformType
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AuthorEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getLong(offset + 1));
        entity.setTimeOut(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setToken(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPullToken(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPlatformType(cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AuthorEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AuthorEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AuthorEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
