package com.meilancycling.mema.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.meilancycling.mema.db.WheelEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WHEEL_ENTITY".
*/
public class WheelEntityDao extends AbstractDao<WheelEntity, Long> {

    public static final String TABLENAME = "WHEEL_ENTITY";

    /**
     * Properties of entity WheelEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property WheelValue = new Property(1, int.class, "wheelValue", false, "WHEEL_VALUE");
        public final static Property Norm = new Property(2, String.class, "norm", false, "NORM");
    }


    public WheelEntityDao(DaoConfig config) {
        super(config);
    }
    
    public WheelEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WHEEL_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"WHEEL_VALUE\" INTEGER NOT NULL ," + // 1: wheelValue
                "\"NORM\" TEXT);"); // 2: norm
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WHEEL_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WheelEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getWheelValue());
 
        String norm = entity.getNorm();
        if (norm != null) {
            stmt.bindString(3, norm);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WheelEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getWheelValue());
 
        String norm = entity.getNorm();
        if (norm != null) {
            stmt.bindString(3, norm);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WheelEntity readEntity(Cursor cursor, int offset) {
        WheelEntity entity = new WheelEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // wheelValue
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // norm
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WheelEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setWheelValue(cursor.getInt(offset + 1));
        entity.setNorm(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WheelEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WheelEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WheelEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
