/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meilancycling_mema_ble_sensor_JniBleController */

#ifndef _Included_com_meilancycling_mema_ble_sensor_JniBleController
#define _Included_com_meilancycling_mema_ble_sensor_JniBleController
#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif
#endif
