/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_meilancycling_mema_ble_sensor_JniBleController */

#ifndef _Included_com_meilancycling_mema_ble_sensor_JniBleController
#define _Included_com_meilancycling_mema_ble_sensor_JniBleController
#ifdef __cplusplus
extern "C" {
#endif

#define GET_JAVA_INT_ID(str)                ((*env)->GetFieldID(env, jcs, str, "I"))
#define GET_JAVA_INT_VALUE(obj, id)         ((*env)->GetIntField(env, obj, id))
#define SET_JAVA_INT_VALUE(obj, id, value)  ((*env)->SetIntField(env, obj, id, value))


#ifdef __cplusplus
}
#endif
#endif
